version: '2.1'
services:
  keycloak:
    image: jboss/keycloak:3.4.3.Final
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    command:
      - "-b 0.0.0.0"
    ports:
      - "8080:8080"
